apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deepspeed-training-
spec:
  entrypoint: deepspeed-training-workflow
  onExit: exit-handler
  templates:
  - name: deepspeed-training-workflow
    steps:
    - - name: create-deepspeed-resources
        template: create-deepspeed-resources
    - - name: detect-pods-fqdn
        template: detect-pods-fqdn
    - - name: run-deepspeed-training
        template: run-deepspeed-training
        arguments:
          artifacts:
          - name: hostfile
            from: "{{steps.detect-pods-fqdn.outputs.artifacts.hostfile}}"
  - name: create-deepspeed-resources
    resource:
      action: apply
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: deepspeed-deployment
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: deepspeed
          template:
            metadata:
              labels:
                app: deepspeed
            spec:
              tolerations:
              - effect: NoSchedule
                key: kubernetes.azure.com/scalesetpriority
                operator: Equal
                value: spot
              - key: "sku"
                operator: "Equal"
                value: "gpu"
                effect: "NoSchedule"
              nodeSelector:
                agentpool: gpua1002
              containers:
              - name: deepspeed-container
                image: nikawang.azurecr.io/deepspeed-bert:v1
                command: ["sh"]
                args: 
                - -c
                - /usr/sbin/sshd -D
                ports:
                - containerPort: 22
                  name: ssh
                resources:
                  requests:
                    nvidia.com/gpu: 1
                  limits:
                    nvidia.com/gpu: 1
                volumeMounts:
                - name: azure
                  mountPath: /app/chk
              volumes:
                - name: azure
                  persistentVolumeClaim:
                    claimName: chk
  - name: detect-pods-fqdn
    container:
      image: alpine/k8s:1.18.2
      command: [sh]
      args: 
      - -c
      - |
        apk add --no-cache curl jq
        STATEFULSET_NAME="deepspeed-deployment"
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        while true; do
          RUNNING_PODS=$(kubectl get pods -l app=deepspeed -n ${NAMESPACE} -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}')
          TOTAL_PODS=$(kubectl get deployment ${STATEFULSET_NAME} -n ${NAMESPACE} -o jsonpath='{.status.replicas}')
          RUNNING_COUNT=$(echo ${RUNNING_PODS} | wc -w)
          if [ "${RUNNING_COUNT}" -eq "${TOTAL_PODS}" ]; then
            echo "所有 Pods 都处于 Running 状态。"
            break
          else
            echo "等待所有 Pods 都变为 Running 状态..."
            sleep 5
          fi
        done
        kubectl get pods -l app=deepspeed -o jsonpath='{.items[*].status.podIP}' | tr -s '[[:space:]]' '\n' | awk '{print $1 " slots=1"}' > /tmp/hostfile
        cat /tmp/hostfile
    outputs:
      artifacts:
      - name: hostfile
        path: /tmp/hostfile
  - name: run-deepspeed-training
    inputs:
      artifacts:
      - name: hostfile
        path: /tmp/hostfile
    volumes:
    - name: azure
      persistentVolumeClaim:
        claimName: chk
    container:
      volumeMounts:
      - name: azure
        mountPath: /app/chk
      image: nikawang.azurecr.io/deepspeed-bert:v1
      # resources:
      #   requests:
      #     nvidia.com/gpu: 1
      #   limits:
      #     nvidia.com/gpu: 1
      command: ["sh"]
      args:
      - -c 
      - |
        echo "localhost slots=1" | cat - /tmp/hostfile > /tmp/temp_hostfile
        cat /tmp/temp_hostfile
        echo "start sshd"
        /usr/sbin/sshd
        sleep 5
        while IFS= read -r line
        do
            # 使用 awk 提取 IP 地址（假设 IP 地址在行的开头）
            IP=$(echo $line | awk '{print $1}')
            echo "Prepare $IP"
            # 执行 ssh-keyscan 并追加到 known_hosts 文件
            ssh-keyscan -H $IP >> /root/.ssh/known_hosts
            
            # 检查 ssh-keyscan 命令是否成功执行
            if [ $? -eq 0 ]; then
                echo "Added $IP to known_hosts."
            else
                echo "Failed to add $IP to known_hosts."
            fi
        done < "/tmp/temp_hostfile"

        echo "All IPs have been processed."
        
        # tail -f /dev/null
        deepspeed --hostfile=/tmp/temp_hostfile train-bert.py --checkpoint_dir ./chk 
    tolerations:
    - effect: NoSchedule
      key: kubernetes.azure.com/scalesetpriority
      operator: Equal
      value: spot
    - key: "sku"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
    nodeSelector:
      agentpool: gpua1002
  - name: exit-handler
    steps:
    - - name: delete-deepspeed-resources
        template: delete-deepspeed-resources
  - name: delete-deepspeed-resources
    container:
      image: alpine/k8s:1.18.2
      command: [sh, -c]
      args: ["kubectl -n argo delete deployment deepspeed-deployment"]
